services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn app.bitpin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge
